### PR TITLE
Put the ca file location in the Certified::CA_FILE constant.

### PR DESCRIPTION
**Pull request by pangloss**
Add a VERSION constant while we're at it.

### CODE REVIEW

**Comment by stevegraham** [comment]
what is the reason for putting this in a constant?

**Comment by pangloss** [comment]
2 reasons: If I want to use the ca file with a different lib, it's easy if
I can grab its location from a constant. Also if I want to inspect the
file, debug an issue with the certificates or just simply know where it is,
it is much easier if that info is available.

For instance when I installed the gem, it didn't work because the path to
the file was relative. I had to waste a bit of time to figure out what was
the issue but If I could have just inspected the constant it would have
been much easier.

Cheers,
Darrick

On Mon, Feb 13, 2012 at 6:34 AM, Stevie Graham <
reply@reply.github.com

**Comment by zkwentz** [comment]
Is there a way we can vote to have this merge request added? This is a good idea.

**Comment by stevegraham** [comment]
@pangloss @zkwentz the problem with this is it makes it possible for other code to change the cert bundle constant.

**Pull request closed without merging**
