### PR TITLE
Use absolute path instead of relative path

### PR DESCRIPTION
**Pull request by jensb1**
This should work independently of your relative path setups

### CODE REVIEW

**Comment by stevegraham** [comment]
thanks!

**Comment by jguice** [comment]
Yeah, please do publish this change as a new revision.  I burned quite a bit of time tracking this down as an issue using the current version (otherwise this is a great, simple solution).

**Comment by stevegraham** [comment]
@mguterl, @jguice done :)

**Comment by jguice** [comment]
Thanks!

**Pull request merged**
